version: "2"
run:
  timeout: 5m
linters:
  default: standard
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - noinlineerr
    - forcetypeassert
    - nonamedreturns
    - mnd
    - godot
    - lll
    - revive
    - gochecknoglobals
    - testpackage
formatters:
  enable:
    - gofmt
